version: '3.7'

services:

  php:
    build:
      context: ./docker/swoole
    container_name: ${DOCKER_APP}-php
    volumes:
      - './:/var/www/html'
    ports:
      - 9503:9503
    networks:
      - my-new-app-network

networks:
  my-new-app-network:
    driver: bridge
